AWSTemplateFormatVersion: "2010-09-09"
Description: Security Groups Template
Outputs:
  SecurityGroupAllId:
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-SecurityGroupAllId
    Value:
      Ref: SecurityGroupAll
  SecurityGroupBastionId:
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-SecurityGroupBastionId
    Value:
      Ref: SecurityGroupBastion
  SecurityGroupVpnId:
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-SecurityGroupVpnId
    Value:
      Ref: SecurityGroupVpn
Parameters:
  VpcId:
    Description: VPC ID to add security groups to.
    Type: String
Resources:
  SecurityGroupAll:
    Properties:
      GroupDescription: Security group for instances accessed via bastion or vpn.
      GroupName: all
      SecurityGroupEgress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        FromPort: 443
        IpProtocol: tcp
        ToPort: 443
      VpcId:
        Ref: VpcId
    Type: AWS::EC2::SecurityGroup
  SecurityGroupBastion:
    Properties:
      GroupDescription: Security group for SSH bastion instances.
      GroupName: bastion
      SecurityGroupEgress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        FromPort: 443
        IpProtocol: tcp
        ToPort: 443
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      VpcId:
        Ref: VpcId
    Type: AWS::EC2::SecurityGroup
  SecurityGroupEgressPlaygroundBastion:
    Properties:
      DestinationSecurityGroupId:
        Fn::GetAtt:
        - SecurityGroupAll
        - GroupId
      FromPort: 22
      GroupId:
        Fn::GetAtt:
        - SecurityGroupBastion
        - GroupId
      IpProtocol: tcp
      ToPort: 22
    Type: AWS::EC2::SecurityGroupEgress
  SecurityGroupEgressPlaygroundVpn:
    Properties:
      DestinationSecurityGroupId:
        Fn::GetAtt:
        - SecurityGroupAll
        - GroupId
      FromPort: 22
      GroupId:
        Fn::GetAtt:
        - SecurityGroupVpn
        - GroupId
      IpProtocol: tcp
      ToPort: 22
    Type: AWS::EC2::SecurityGroupEgress
  SecurityGroupIngressBastionPlayground:
    Properties:
      FromPort: 22
      GroupId:
        Fn::GetAtt:
        - SecurityGroupAll
        - GroupId
      IpProtocol: tcp
      SourceSecurityGroupId:
        Fn::GetAtt:
        - SecurityGroupBastion
        - GroupId
      ToPort: 22
    Type: AWS::EC2::SecurityGroupIngress
  SecurityGroupIngressVpnPlayground:
    Properties:
      FromPort: 22
      GroupId:
        Fn::GetAtt:
        - SecurityGroupAll
        - GroupId
      IpProtocol: tcp
      SourceSecurityGroupId:
        Fn::GetAtt:
        - SecurityGroupVpn
        - GroupId
      ToPort: 22
    Type: AWS::EC2::SecurityGroupIngress
  SecurityGroupVpn:
    Properties:
      GroupDescription: Security group for VPN instances.
      GroupName: vpn
      SecurityGroupEgress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        FromPort: 443
        IpProtocol: tcp
        ToPort: 443
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIp: 0.0.0.0/0
        FromPort: 1194
        IpProtocol: udp
        ToPort: 1194
      - CidrIp: 0.0.0.0/0
        FromPort: 943
        IpProtocol: tcp
        ToPort: 943
      - CidrIp: 0.0.0.0/0
        FromPort: 443
        IpProtocol: tcp
        ToPort: 443
      VpcId:
        Ref: VpcId
    Type: AWS::EC2::SecurityGroup
