AWSTemplateFormatVersion: "2010-09-09"
Description: Internal Instance Template
Parameters:
  DnsName:
    Description: FQDN to use for the service
    Type: String
  ElbSecurityGroupId:
    Description: Security group to attach to instance.
    Type: String
  Namespace:
    Description: A unique name to associate with resources for tagging purposes.
    Type: String
  PlaygroundSecurityGroupId:
    Description: Security group to attach to instance.
    Type: String
  SubnetId:
    Description: ID of the subnet to place the instance in.
    Type: String
  ZoneId:
    Description: Route53 zone to add the service DNS records to.
    Type: String
Resources:
  AutoScalingGroup:
    Properties:
      AutoScalingGroupName:
        Fn::Sub: ${Namespace}-asg-playground
      LaunchConfigurationName:
        Ref: LaunchConfiguration
      LoadBalancerNames:
      - Ref: LoadBalancer
      MaxSize: "1"
      MinSize: "1"
      Tags:
      - Key: Name
        PropagateAtLaunch: true
        Value:
          Fn::Sub: ${Namespace}-asg-playground
      VPCZoneIdentifier:
      - Ref: SubnetId
    Type: AWS::AutoScaling::AutoScalingGroup
  DnsRecord:
    Properties:
      HostedZoneId:
        Ref: ZoneId
      Name:
        Ref: DnsName
      ResourceRecords:
      - Fn::GetAtt:
        - LoadBalancer
        - DNSName
      TTL: "300"
      Type: CNAME
    Type: AWS::Route53::RecordSet
  LaunchConfiguration:
    Properties:
      ImageId: ami-0ff8a91507f77f867
      InstanceType: t3.micro
      KeyName: akerr-lab-key
      SecurityGroups:
      - Ref: PlaygroundSecurityGroupId
      UserData:
        Fn::Base64:
          Fn::Sub: []
    Type: AWS::AutoScaling::LaunchConfiguration
  LoadBalancer:
    Properties:
      HealthCheck:
        HealthyThreshold: "2"
        Interval: "15"
        Target: TCP:22
        Timeout: "10"
        UnhealthyThreshold: "2"
      Listeners:
      - InstancePort: "22"
        InstanceProtocol: TCP
        LoadBalancerPort: "22"
        Protocol: TCP
      Scheme: internal
      SecurityGroups:
      - Ref: ElbSecurityGroupId
      Subnets:
      - Ref: SubnetId
    Type: AWS::ElasticLoadBalancing::LoadBalancer
