AWSTemplateFormatVersion: "2010-09-09"
Description: Internal Instance Template
Parameters:
  DnsName:
    Description: FQDN to use for the service
    Type: String
  ElbSecurityGroupId:
    Description: Security group to attach to instance.
    Type: String
  PlaygroundSecurityGroupId:
    Description: Security group to attach to instance.
    Type: String
  SubnetId:
    Description: ID of the subnet to place the instance in.
    Type: String
  ZoneId:
    Description: Route53 zone to add the service DNS records to.
    Type: String
Resources:
  DnsRecord:
    Properties:
      HostedZoneId:
        Ref: ZoneId
      Name:
        Ref: DnsName
      ResourceRecords:
      - Fn::GetAtt:
        - Instance
        - PrivateIp
      TTL: "300"
      Type: A
    Type: AWS::Route53::RecordSet
  Instance:
    Properties:
      ImageId: ami-0ff8a91507f77f867
      InstanceType: t3.micro
      KeyName: akerr-lab-key
      SecurityGroupIds:
      - Ref: PlaygroundSecurityGroupId
      SubnetId:
        Ref: SubnetId
    Type: AWS::EC2::Instance
  LoadBalancer:
    Properties:
      HealthCheck:
        HealthyThreshold: "2"
        Interval: "15"
        Target: TCP:22
        Timeout: "10"
        UnhealthyThreshold: "2"
      Listeners:
      - InstancePort: "22"
        InstanceProtocol: TCP
        LoadBalancerPort: "22"
        Protocol: TCP
      SecurityGroups:
      - Ref: ElbSecurityGroupId
      Subnets:
      - Ref: SubnetId
    Type: AWS::ElasticLoadBalancing::LoadBalancer
