AWSTemplateFormatVersion: "2010-09-09"
Description: Internal Instance Template
Parameters:
  SecurityGroupId:
    Type: String
  SubnetId:
    Type: String
Resources:
  Instance:
    Properties:
      ImageId: ami-0ff8a91507f77f867
      InstanceType: t3.micro
      KeyName: akerr-lab-key
      SecurityGroupIds:
      - Ref: SecurityGroupId
      SubnetId:
        Ref: SubnetId
    Type: AWS::EC2::Instance
