AWSTemplateFormatVersion: "2010-09-09"
Description: Internal Role
Resources:
  Role:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
        Version: "2012-10-17"
      Description: IAM role internal instances.
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/ReadOnlyAccess
      RoleName: internal-role
    Type: AWS::IAM::Role
