AWSTemplateFormatVersion: "2010-09-09"
Description: Bastion Instance Template
Parameters:
  DnsName:
    Description: FQDN to use for the service
    Type: String
  SecurityGroupId:
    Description: Security group to attach to instance.
    Type: String
  SubnetId:
    Description: ID of the subnet to place the instance in.
    Type: String
  ZoneId:
    Description: Route53 zone to add the service DNS records to.
    Type: String
Resources:
  DnsRecord:
    Properties:
      HostedZoneId:
        Ref: ZoneId
      Name:
        Ref: DnsName
      ResourceRecords:
      - Ref: EIP
      TTL: "300"
      Type: A
    Type: AWS::Route53::RecordSet
  EIP:
    Properties:
      Domain: vpc
    Type: AWS::EC2::EIP
  EIPAssociation:
    Properties:
      AllocationId:
        Fn::GetAtt:
        - EIP
        - AllocationId
      InstanceId:
        Ref: Instance
    Type: AWS::EC2::EIPAssociation
  Instance:
    Properties:
      ImageId: ami-0ff8a91507f77f867
      InstanceType: t3.micro
      KeyName: akerr-lab-key
      SecurityGroupIds:
      - Ref: SecurityGroupId
      SubnetId:
        Ref: SubnetId
    Type: AWS::EC2::Instance
